### ISSUE TITLE
Implementing multiple changes

### ISSUE THREAD

**Issue by jide** [PowToon/redux-undo-redo#3]
The docs says :
> Easily support multiple changes that should be treated as a single undo step. (animation, drag drop)

How can this be implemented ?

**Comment by vzaidman** [comment]
You send an `DRAG_START` and create a reverting action to return to the state when this action is sent.

You send your `DRAG_PROGRESS` events with no reverting action.

Now if a user reverts his action, he will return to the state when `DRAG_START` was sent before the `PROGRESS_ACTION`s

**Comment by vzaidman** [comment]
Lets say you start with `{state: {a: something, tempA: undefined}}`.

You dispatch `DO_SOMETHING_START` to copy `state.a` to `state.tempA`.

You dispatch `DO_SOMETHING_PROGRESS` actions to work on `state.tempA`.

a selector selects `a` from the state as `tempA || a`

When it's done you dispatch `DO_SOMETHING_END` that copies `tempA` to `a` and deletes `tempA` and have a reverting action to go back to the previous `state.a`

Now if the user presses "undo", `a` becomes the previous `a`.
When the user presses "redo", `a` becomes the new `a` again.

**Comment by jide** [comment]
Thank you, I'll try this !

**Comment by arikmaor** [comment]
@jide did you get your project to work?

**Comment by jide** [comment]
Yes, in the end I used the idea with redux-undo, on which the project depended too much to switch to redux-undo-redo.
