### ISSUE TITLE
Allow limiting history

### ISSUE THREAD

**Issue by modsushi** [PowToon/redux-undo-redo#6]
How should I go about limiting the undo history or clear all of it?

**Comment by vzaidman** [comment]
Well, you can add a PR about this.

For now, wrap the `undoHistoryReducer` and manipulate the history as you wish:

```
import {combineReducers} from 'redux'
import {undoHistoryReducer} from 'redux-undo-redo'

import {appReducer} from './app'
import {someOtherReducer} from './someOtherModule'

const customUndoHistoryReducer = (state, action) => {
  ...
  const newState = undoHistoryReducer(state, action)
  ...
}

const rootReducer = combineReducers({
  app: appReducer,
  other: someOtherReducer,
  undoHistory: customUndoHistoryReducer 
})
```

**Comment by modsushi** [comment]
that works for me. Also is it possible to have multiple history reducers? Bound to different containers.

**Comment by vzaidman** [comment]
No.
I added an issue with an explanation of how to implement this enhancement. We don't currently need it and I don't think we will implement it in the near future: https://github.com/PowToon/redux-undo-redo/issues/7.

A pull request, however, for any of these issues will be welcome and addressed immediately.

Thanks.
